plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':product-domain')
    implementation project(':product-application')
    implementation project(':product-infrastructure')

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'io.micrometer:micrometer-tracing-bridge-otel'
    implementation 'io.opentelemetry:opentelemetry-exporter-otlp'
    implementation 'io.micrometer:context-propagation'

    testImplementation 'org.springframework.security:spring-security-test'
}
